### ISSUE TITLE
ShowPlayerDialog, spawn bug, js/samp.js/Player.js, mysql.ping, mysql.close

### ISSUE THREAD

**Issue by Laronic** [damospiderman/samp.js#32]
`samp.js v0.1.9.2`
`win8.1`
- `ShowPlayerDialog` is not getting shown
- Whenever I spawn, I'm given a shovel, and it gets removed when i scroll to fists
- In `js/samp.js/Player.js` some of the setters still use `this._id` (which has been renamed to `this.id`?)
- `conn.ping()` returns `undefined`
- `conn.close()` crashes the server

_Test code:_

``` javascript
include('js/include/a_samp.inc.js');
include('js/include/a_players.inc.js');

var conn = $mysql.createConnection(stuff...);
conn.connect(function(err)
{
    if(err) {
        return print(`[mysql] ${err}`);
    }
    print(`ping: ${conn.ping()}`); //ping: undefined
});

$server.on("GameModeInit", function()
{
    AddPlayerClass(0, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0);
    return 1;
});

$server.on("GameModeExit", function()
{
    conn.close(); //server crash
    return 1;
});

$server.on("PlayerCommandText", function(player, cmdtext) 
{
    if(cmdtext == '/dia')
    {
        ShowPlayerDialog(player.id, 0, DIALOG_STYLE_MSGBOX, "Test", "Hello World!", "kk", "nop");
        return true;
    }
    return 0;
});

$server.on("PlayerRequestClass", function(player, classid) {
    return 1;
});

$server.on("PlayerRequestSpawn", function(player) {
    return 1;
});
```

**Comment by damopewpew** [comment]
Sorry for the delay on this fix, busy day at work and wanted to make sure all issues were fixed and tested correctly.

You can download the new release here https://github.com/damospiderman/samp.js/releases/tag/v0.1.9.3

Note that I couldn't reproduce the issue with the shovel, but I could have indirectly fixed it in some of my other changes.

**Comment by Laronic** [comment]
No problem

Seems like the shovel issue has been fixed as well in this update, thanks again!
