### ISSUE TITLE
RCON commands: reloadjs, loadjs, unloadjs not work

### ISSUE THREAD

**Issue by andievandy** [damospiderman/samp.js#33]
those commands were working in v0.1.8.1. But since v1.9 they do nothing.
is it bug or intended? any chance for getting those back?

Thanks

**Comment by damopewpew** [comment]
They are working with 0.1.9.3 but due to limitations with samp you need to have at least one filterscript loaded for them to work

**Comment by andievandy** [comment]
ah I see..

thanks for the reply..
