### ISSUE TITLE
KillTimer, SetTimerEx, some player.(thing) problem

### ISSUE THREAD

**Issue by andievandy** [damospiderman/samp.js#34]
using samp.js v0.1.9.3 on SAMP 0.3.7 R2-1 server running on Windows 8.1
- `KillTimer` doesn't stop active timer, is it bug or am I doing something wrong?
- `KillTimer` on `ScriptExit` callback crashes the server.
- `SetTimerEx` returns timer id but the function doesn't get called.
- `player.health` can't be set, but works via SetPlayerHealth
- `player.armour`, `player.score`, `player.skin`, `player.wantedLevel` same problem as `player.health`

Here's the code:

``` javascript
/**
 * Remake of new.pwn in samp.js/JavaScript 
 **/

include("js/include/a_samp.inc.js");
include("js/include/a_players.inc.js");
include("js/include/a_vehicles.inc.js");
include("js/include/a_objects.inc.js");
include("js/include/a_sampdb.inc.js");

var nitrotimer, nitrotimer2

$server.on("ScriptInit",function()
{
    print("\n----------------------------------");
    print(" test");
    print("----------------------------------\n");
    nitrotimer = SetTimer(nitrotest, 1000, -1);
    print(nitrotimer);
    nitrotimer2 = SetTimerEx(nitrotest2, 1000, -1, "90");
    print(nitrotimer2);

    KillTimer(nitrotimer);
});

function nitrotest()
{
    print("before kill");
    KillTimer(nitrotimer);
    print("after kill");
    return 1;
}

function nitrotest2(number)
{
    print(`response: ${number}`);
}

$server.on("ScriptExit",function()
{
    print("\n----------------------------------");
    print(" test unloaded");
    print("----------------------------------\n");
    KillTimer(nitrotimer);
});


$server.on("PlayerCommandText",function(player, cmdtext)
{
    var args = cmdtext.split(' ');
    var cmd = args.shift();

    if(cmd == "/kill")
    {
        SetPlayerHealth(player, -1.0); //works
        return 1;
    }
    if(cmd == "/kill2")
    {
        player.health = -1.0; //doesn't work
        player.armour = 50;
        player.score = -1;
        player.wantedLevel = 3;
        player.skin = 299;
        return 1;
    }
    return 0;
});

```

Anyway, keep up the good work! :D

**Comment by damopewpew** [comment]
Ok Timers are something I should probably explain a bit more. SetTimer is a native samp.js function where as SetTimerEx and KillTimer are just wrappers around samp functions which should be removed. 

So we have SetTimer and CancelTimer

``` javascript
// -1 timer repeats forever every 1000ms
let timerid = SetTimer(function(){
    CancelTimer(timerid);
}, 1000, -1 );
// 0 - Timer runs once only after 1000ms and calls somefunc
let timerid2 = SetTimer(somefunc, 1000, 0);

function somefunc(){

}

// Timer runs 5 times every 1000ms
let timerid3 = SetTimer(function(){}, 1000, 5 );

// Now we can also replicate SetTimerEx with some javascript tricks

$server.on("PlayerConnect", function(player){
    SetTimer(function(player){

    }.bind(this, player), 1000, 0 );

    SetTimer(doSomething.bind(this,player), 1000, 0 );
});


function doSomething(player){

}
```

Hope that all makes sense. I will get back to you with the player issues once I get a chance to test

**Comment by andievandy** [comment]
Ah now I get it, thanks for the explanation about timers stuff..

also looking forward for the player issues :D, hope it will get fixed soon..

**Comment by damopewpew** [comment]
Ok I found the player issue. There were some variables named incorrectly ( probably due to find/replace ). 

If you can use this https://github.com/damospiderman/samp.js/blob/master/server/js/samp.js/Player.js that should fix your issues. Also added player.message( color, message );

**Comment by andievandy** [comment]
ah nice, some of those are working now, thanks for the fix. but `player.score` still not working..

EDIT: okay got the fix, may I do pull request? I also added `player.world`

**Comment by damopewpew** [comment]
Yeah I just fixed it but feel free to do a pull request with your other changes :)

**Comment by andievandy** [comment]
okay, I have created the pull request

so these Issues are fixed now, thanks :D
