### ISSUE TITLE
Several callbacks doesn't pass to another script if it doesn't return 0

### ISSUE THREAD

**Issue by andievandy** [damospiderman/samp.js#36]
okay I don't know how to explain this..

example there are 2 loaded script
script 1:

``` javascript
$server.on("PlayerConnect",function(player)
{
    SendClientMessage(player, 0xFF004040, "PlayerConnect script1.");
    return 1;
});
```

 Script 2:

``` javascript
$server.on("PlayerConnect",function(player)
{
    SendClientMessage(player, 0xFF004040, "PlayerConnect script2.");
    return 0;
});
```

When player connects, `PlayerConnect` callback in Script 1 get called but Script 2 doesn't. but when I change the callback return to 0 in Script 1:

``` javascript
$server.on("PlayerConnect",function(player)
{
    SendClientMessage(player, 0xFF004040, "PlayerConnect script1.");
    return 0;
});
```

`PlayerConnect` callback get called on both script.

So it just like `PlayerCommandText` and `OnDialogResponse` callbacks.

Tested on `PlayerConnect`, `PlayerRequestSpawn`, `PlayerDisconnect`.
Am I do something wrong again? no other plugins loaded.

**Comment by damopewpew** [comment]
No you're not doing anything wrong. This would be because of something I've done wrong with sampgdk I'm guessing. SA-MP makes things tricky with the fact that its not consistent with its return values, so I've had to do annoying work arounds. I will look over my code and see where it goes wrong.

**Comment by andievandy** [comment]
ah okay, looking for the fix then.. :D

**Comment by damopewpew** [comment]
Found the issue and fixed

Use this https://github.com/damospiderman/samp.js/blob/master/bin/samp.js.dll

**Comment by andievandy** [comment]
Now the callback on Script 2 doesn't get called if I don't define the callback on Script 1..
and `PlayerRequestSpawn` doesn't get called on other script either if i return 1 or 0

**Comment by damopewpew** [comment]
Use this https://github.com/damospiderman/samp.js/blob/master/server/js/samp.js/Events.js

**Comment by andievandy** [comment]
seems they are working fine now, thanks :D
