### ISSUE TITLE
PlayerCommandText, SQLite problem

### ISSUE THREAD

**Issue by andievandy** [damospiderman/samp.js#44]
using v0.1.9.5 on SA-MP 0.3.7 R2 server running on Windows 10.
- PlayerCommand always show "SERVER: Unknown command." even if I have returned 1 on script.

``` javascript
$server.on("PlayerCommandText",function(player, cmdtext)
{
    var args = cmdtext.split(' ');
    var cmd = args.shift();

    if (cmd == "/testcmd")
    {
        SendClientMessage(player, 0xFF004040, "CMD test");
        return 1;
    }
    return 0;
});
```

```
[16:23:37] CMD test

[16:23:37] SERVER: Unknown command.
```

in v0.1.9.4 it works fine without that message.
- I can't get any value from db_get_field_assoc, db_get_field, db_field_name. Any chance for fixing it?

EDIT:
- How to make function or variable that can be accessed in other scripts?

Anyway, great update! :D

**Comment by damopewpew** [comment]
My fix for streamer callbacks crashing the server must have broken return values, I will look into it

I'll have a look at the sqlite stuff, might end up implementing a sqlite for samp.js like the mysql one

Currently there's no real way to send variables etc between scripts but I've been meaning to implement it so I'll think up a good solution for you

**Comment by damopewpew** [comment]
Ok I have fixed all of these and they will be in the next update.

The sqlite stuff the function signatures were wrong and have been updated to the correct ones.

As for making variables available in other scripts I have added a $server.emit() method so you can do

```
$server.emit("someevent", var1, var2, var3 );

// Another script
$server.on("someevent", function(var1,var2,var3){

});
```

I will probably extend this later to have some kind of sync'd variables, if it doesn't give me too much of a headache

**Comment by andievandy** [comment]
that's awesome :D thanks so much, can't wait for the next update..

**Comment by damopewpew** [comment]
Released. Enjoy
